version: "3.8"
services:
  nodebackend:
    image: nodebackend:latest
    container_name: node-backend
    restart: always
    build: .
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
